name: CI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and Test
    permissions:
      contents: read
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get rust version
        run: rustc --version --verbose
      - name: Get cargo version
        run: cargo --version --verbose
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
          key: server-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build -r
      - name: Lint
        run: cargo clippy -r --all-targets --all-features -- -Dwarnings
      - name: Run unit tests
        run: cargo test -r
