name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build
    permissions:
      contents: read
    strategy:
      matrix:
       # os: [macos-26-intel, macos-latest, ubuntu-latest, , ubuntu-24.04-arm, windows-latest, windows-11-arm]
       os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get rust version
        run: rustc --version --verbose
      - name: Get cargo version
        run: cargo --version --verbose
      - name: Build
        run: cargo build -release
      - name: Zip
        run: tar -a -cf cryptcrypt_${{ runner.os }}_${{ runner.arch }}.zip target/release/cryptcrypt
      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: Binary for ${{ runner.os }} ${{ runner.arch }}
          path: cryptcrypt_${{ runner.os }}_${{ runner.arch }}.zip