name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build
    permissions:
      contents: read
    strategy:
      matrix:
       os: [macos-26-intel, macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get rust version
        run: rustc --version --verbose
      - name: Get cargo version
        run: cargo --version --verbose
      - name: Build
        run: cargo build --release
      - name: Prepare Test (Windows)
        if: runner.os == 'Windows'
        # wexpect needs pkg_resources, therefore older setuptools (which still contains it) required
        run: pip install setuptools==81.0.0 wexpect
      - name: Prepare Test (macOS)
        if: runner.os == 'macOS'
        run: pip install pexpect
      - name: Test
        run: python .github/workflows/test_release.py
      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: cryptcrypt_${{ runner.os }}_${{ runner.arch }}
          path: target/release/cryptcrypt${{ runner.os == 'Windows' && '.exe' || '' }}
          compression-level: 0